name: OpenLane Flow

on: [push]

jobs:
  run-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Run OpenLane
        run: |
          docker run -v ${{ github.workspace }}:/project \
            efabless/openlane:latest \
            bash -c "cd /project && flow.tcl -design my_design"
