name: OpenLane Flow

on: [push]

jobs:
  run-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run OpenLane
        run: |
          docker run --rm -v ${{ github.workspace }}:/openlane \
            efabless/openlane:latest \
            ./flow.tcl -design my_project
