name: OpenLane Flow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-openlane:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull OpenLane Docker image
      run: docker pull ghcr.io/the-openroad-project/openlane:latest

    - name: Run OpenLane flow
      run: |
        docker run --rm -v ${{ github.workspace }}:/project \
        -v /tmp/volare:/home/openlane/.volare \
        -e PDK=sky130A \
        -e PDK_ROOT=/home/openlane/.volare/sky130 \
        ghcr.io/the-openroad-project/openlane:latest \
        bash -c "cd /project && flow.tcl -design . -run_path runs/gha_run"

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: openlane-results
        path: runs/gha_run

