name: OpenLane Flow

on:
  push:
    branches:
      - main
      - '**'   # run on all branches (optional)

jobs:
  run-openlane:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run OpenLane Flow
        run: |
          docker run --rm -v ${{ github.workspace }}:/openlane \
            -w /openlane/openlane \
            efabless/openlane:latest \
            ./flow.tcl -designs_dir designs/picosoc/designs/my_project
